### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by gegentan** [lilmayu/ColoredEndCrystals#1]
![Screenshot_2024-06-09-02-18-58-59_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/lilmayu/ColoredEndCrystals/assets/120120135/6b89f687-6336-443f-9ac3-2fae91251093)

**Comment by gegentan** [comment]
Btw I'm not sure because it's "a different form of more".

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
@gegentan i didn't get it please what is the issue ? and how can i help ?

**Comment by gegentan** [comment]
I mean, I think that "moar" is a typo. I THINK

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
'moar' should be 'more', i understand, how can we be sure ?

**Comment by lilmayu** [comment]
This is intended :P
